### ISSUE TITLE
Building for iOS using with Unity 2020

### ISSUE THREAD

**Issue by wchacn** [microsoft/MapsSDK-Unity#108]
**Describe the bug**
Hi, we tried to build the our own app based on the SDK with Unity 2020.2.6f1. Works flawlessly for UWP and Android, however, when building for iOS, Xcode throws some semantic errors:

<img width="1009" alt="Screenshot 2021-03-15 at 14 43 09" src="https://user-images.githubusercontent.com/80388513/111183080-d4bf2600-85af-11eb-8bfd-f55f2d4819b3.png">

Any idea what could be the underlying issue here?

Is there generally a plan to support Unity 2020?

Thanks a lot!

**To Reproduce**
1. Build sample app with Unity 2020.6f1 for iOS and try to build in Xcode

**Environment (please complete the following information):**
 - Unity version: 2020.2.6f1
 - Maps SDK Package version: latest

**Comment by kircher1** [comment]
Thanks for the bug report. This looks like a possible regression in Unity. IL2CPP is expanding the DLL import path with the slashes into a code define. Since the slash isn't a valid character for a `#define`, there will be compilation errors. I haven't seen this in 2019.4.

**Comment by OneMilkTwoStraws** [comment]
Same problem here with Unity2020.2 - help will be highly appreciated!

**Comment by RomArtefacto** [comment]
It seems to be the same on Android (with IL2CCP) -> tested with Unity 2020.3.0 and 2020.3.1
Thanks in advance for your help !

**Comment by kircher1** [comment]
This should be fixed on 10.2-- I've verified IL2CPP builds on Android and iOS (simulator) for 2020.3. Let me know if there are any further issues. Thanks!

**Comment by OneMilkTwoStraws** [comment]
Thanks a lot for the solution! It works perfectly on iOS after building with Unity 2020.3 :) Now we can build on all platforms again - have a great weekend.
